### ISSUE TITLE
Redundant Link for Dapp Users

### ISSUE THREAD

**Issue by Fingerling42** [airalab/blackmirror-dapp#2]
After sending the transaction, the link does not lead anywhere. It should be removed, because we have checking dapp. 

![image](https://user-images.githubusercontent.com/17783902/207964158-a6045750-59fb-4853-9c22-50ae7826e2db.png)

**Comment by vol4tim** [comment]
Removed link and accounts page. https://github.com/airalab/blackmirror-dapp/commit/339f032e0b54ddd8f21f04e9de6548902dde6661
